-- TABLE
CREATE TABLE CLIENTE (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nome VARCHAR(80) NOT NULL, email VARCHAR(40) NOT NULL, TELEFONE INTEGER);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
