-- TABLE
CREATE TABLE cliente (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nome VARCHAR(80) NOT NULL, idade INTEGER NOT NULL, cpf VARCHAR(20) NOT NULL, rg VARCHAR(20) NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
